version: "3"
services:

  memcached:
    hostname: memcached
    image: memcached:latest
    ports:
      - "11211:11211"

  graphql:
    profiles: [ "graphql" ]
    build:
      context: graph
      dockerfile: Dockerfile
    hostname: graphql
    ports:
      - "7007:7007"
    env_file:
      - rtb.env
    volumes:
      - ./../files:/app/files:rw
    depends_on:
      - webapp

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: webapp
    ports:
      - "8888:8888"
    volumes:
      - ./files:/opt/rtb/files:rw
    env_file:
      - rtb.env
    restart: always
    depends_on:
      memcached:
        condition: service_started
      mariadb:
        condition: service_healthy
      webapp_start:
        condition: service_completed_successfully

  webapp_start:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "python3", "/opt/rtb/rootthebox.py", "--setup=prod" ]
    volumes:
      - ./files:/opt/rtb/files:rw
    env_file:
      - rtb.env
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:latest
    hostname: mariadb
    restart: always
    env_file:
      - rtb.env
    ports:
      - '3306:3306'
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "--user=${MYSQL_USER}",
          "--password=${MYSQL_PASSWORD}",
          "ping",
          "--silent"
        ]
      timeout: 20s
      retries: 10
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
