version: "3"
services:

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  graph:
    build: graph
    ports:
      - "7007:7007"
    volumes:
      - ./../files:/app/files:rw
    depends_on:
      - webapp

  webapp:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./files:/opt/rtb/files:rw
    depends_on:
      - postgres
      - memcached

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=rtb
      - POSTGRES_PASSWORD=XHb6&oUUQy973
      - POSTGRES_DB=rootthebox
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      #- ./setup/dbupdate.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: info@leonardocompany.com
      PGADMIN_DEFAULT_PASSWORD: U4AOm9588^MP
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
